version: 2

project_name: kaedama
builds:
  - id: kaedama
    binary: kaedama
    main: ./
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    gcflags:
      - -N
      - -l
    hooks:
      pre:
        - go test ./...

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: khatibomar
    name: kaedama

changelog:
  use: github